name: Platforms compatibility check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Build NativeAOT for linux-x64
      run: dotnet publish -r linux-x64 -warnaserror /p:RunAnalyzers=true

    - name: Build NativeAOT for linux-arm64
      run: dotnet publish -r linux-arm64 -warnaserror /p:RunAnalyzers=true

    - name: Build NativeAOT for linux-arm
      run: dotnet publish -r linux-arm -warnaserror /p:RunAnalyzers=true

    - name: Build NativeAOT for win-x64
      run: dotnet publish -r win-x64 -warnaserror /p:RunAnalyzers=true

    - name: Build NativeAOT for win-arm64
      run: dotnet publish -r win-arm64 -warnaserror /p:RunAnalyzers=true

    - name: Build NativeAOT for win-x86
      run: dotnet publish -r win-x86 -warnaserror /p:RunAnalyzers=true

    - name: Build NativeAOT for osx-x64
      run: dotnet publish -r osx-x64 -warnaserror /p:RunAnalyzers=true

    - name: Build NativeAOT for osx-arm64
      run: dotnet publish -r osx-arm64 -warnaserror /p:RunAnalyzers=true